### ISSUE TITLE
💡 [FEAT] Option to hide, strike-through or dim completed tasks

### ISSUE THREAD

**Issue by silentjay** [dooit-org/dooit#191]
For workspaces with a lot of recurring tasks it can get overwhelming to see all the tasks, especially for recurring tasks you can't delete once complete. I think it would might be an idea to have an option to dim/hide these tasks until the day they are due again, maybe with a keybinding to unhide/un-dim etc 

For now a simple workout around is that i'm going to move all my recurring tasks to their own workspace.

**Comment by kraanzu** [comment]
Hi @silentjay, Yes I'm working on a feature that'd allow you to customize how you see your tasks. The new version should be released in <10 days

**Comment by kraanzu** [comment]
Hi @silentjay, sorry for the delay! This is now possible. Check [Strike Completed](https://dooit-org.github.io/dooit-extras/formatters/description.html#strike-completed)

Also, check out the newer docs since a whole lot has changed :)

Note: Hide is not possible as of now, there are similar requests that want same behaviours (ie changing the items displayed in the list) so I'll think of the a good implementation in the next release :)

**Comment by silentjay** [comment]
The new strike completed functionality is good enough for me, looks better than I thought. Hiding isn't necessary for me now we can dim/strike out completed todos although others may still want this.

**Comment by kraanzu** [comment]
Lets gooo! Glad that you liked this

**Comment by kraanzu** [comment]
Hey @silentjay , not sure about your familiarity with python or programming in general, but how would you rate the [Formatter Section](http://localhost:5173/dooit/configuration/formatter.html) on a scale of 10 for clarity to the users?

**Comment by kraanzu** [comment]
Awesome. Glat to hear that <3

**Comment by kraanzu** [comment]
> Oh and I forgot to mention had an issue with the migration command, didn't note the error sadly but it wouldn't import my todos.

Yes my bad. Please check out the latest version, its fixed
